import { normalizeMeasurements } from "./measurements.js";

function profile({ id, label, description, measurements }) {
  return {
    id,
    label,
    description,
    measurements: normalizeMeasurements(measurements)
  };
}

export const silhouetteQaProfiles = [
  profile({
    id: "compact-light-frame",
    label: "Compact light frame",
    description: "Shorter, lighter user with narrow shoulders and small limb spans.",
    measurements: {
      sex: "female",
      height: 152,
      weight: 48,
      headCircumference: 53,
      neckCircumference: 29,
      biacromialWidth: 32,
      bideltoidWidth: 39,
      bideltoidCircumference: 85,
      armpitCircumference: 74,
      nippleCircumference: 78,
      underbustCircumference: 70,
      waistCircumference: 61,
      pantWaistCircumference: 68,
      hipCircumference: 84,
      upperThighCircumference: 43,
      midThighCircumference: 38,
      calfCircumference: 30,
      ankleCircumference: 18,
      bicepCircumference: 22,
      upperForearmCircumference: 19,
      wristCircumference: 13
    }
  }),
  profile({
    id: "tall-broad-frame",
    label: "Tall broad frame",
    description: "Very tall user with broad shoulders, large torso spans, and above-average limb girths.",
    measurements: {
      sex: "male",
      height: 198,
      weight: 112,
      headCircumference: 60,
      neckCircumference: 44,
      biacromialWidth: 50,
      bideltoidWidth: 64,
      bideltoidCircumference: 145,
      armpitCircumference: 123,
      nippleCircumference: 118,
      underbustCircumference: 112,
      waistCircumference: 94,
      pantWaistCircumference: 98,
      hipCircumference: 108,
      upperThighCircumference: 68,
      midThighCircumference: 58,
      calfCircumference: 44,
      ankleCircumference: 26,
      bicepCircumference: 42,
      upperForearmCircumference: 34,
      wristCircumference: 19
    }
  }),
  profile({
    id: "waist-hip-curvy",
    label: "Waist-hip curvy",
    description: "Pronounced waist-to-hip contrast with wider hips and thighs.",
    measurements: {
      sex: "female",
      height: 168,
      weight: 72,
      headCircumference: 55,
      neckCircumference: 33,
      biacromialWidth: 36,
      bideltoidWidth: 45,
      bideltoidCircumference: 104,
      armpitCircumference: 91,
      nippleCircumference: 98,
      underbustCircumference: 81,
      waistCircumference: 70,
      pantWaistCircumference: 82,
      hipCircumference: 114,
      upperThighCircumference: 66,
      midThighCircumference: 56,
      calfCircumference: 38,
      ankleCircumference: 22,
      bicepCircumference: 29,
      upperForearmCircumference: 24,
      wristCircumference: 15
    }
  }),
  profile({
    id: "narrow-frame-lean",
    label: "Narrow frame lean",
    description: "Average-height lean user with narrow shoulders and lower circumference values.",
    measurements: {
      sex: "male",
      height: 178,
      weight: 68,
      headCircumference: 56,
      neckCircumference: 35,
      biacromialWidth: 34,
      bideltoidWidth: 41,
      bideltoidCircumference: 96,
      armpitCircumference: 86,
      nippleCircumference: 84,
      underbustCircumference: 80,
      waistCircumference: 73,
      pantWaistCircumference: 78,
      hipCircumference: 88,
      upperThighCircumference: 50,
      midThighCircumference: 43,
      calfCircumference: 35,
      ankleCircumference: 21,
      bicepCircumference: 28,
      upperForearmCircumference: 24,
      wristCircumference: 15
    }
  }),
  profile({
    id: "high-bmi-central-mass",
    label: "High BMI central mass",
    description: "Higher body mass with larger waist, hip, chest, and neck measurements.",
    measurements: {
      sex: "male",
      height: 172,
      weight: 118,
      headCircumference: 58,
      neckCircumference: 47,
      biacromialWidth: 42,
      bideltoidWidth: 56,
      bideltoidCircumference: 142,
      armpitCircumference: 132,
      nippleCircumference: 130,
      underbustCircumference: 124,
      waistCircumference: 128,
      pantWaistCircumference: 132,
      hipCircumference: 134,
      upperThighCircumference: 75,
      midThighCircumference: 66,
      calfCircumference: 46,
      ankleCircumference: 28,
      bicepCircumference: 40,
      upperForearmCircumference: 34,
      wristCircumference: 20
    }
  }),
  profile({
    id: "endurance-lean",
    label: "Endurance lean",
    description: "Tall lean user with low waist and moderate shoulders.",
    measurements: {
      sex: "male",
      height: 184,
      weight: 70,
      headCircumference: 57,
      neckCircumference: 36,
      biacromialWidth: 39,
      bideltoidWidth: 48,
      bideltoidCircumference: 104,
      armpitCircumference: 88,
      nippleCircumference: 86,
      underbustCircumference: 82,
      waistCircumference: 69,
      pantWaistCircumference: 75,
      hipCircumference: 90,
      upperThighCircumference: 50,
      midThighCircumference: 43,
      calfCircumference: 34,
      ankleCircumference: 21,
      bicepCircumference: 28,
      upperForearmCircumference: 25,
      wristCircumference: 16
    }
  }),
  profile({
    id: "lower-body-dominant",
    label: "Lower-body dominant",
    description: "Wider hip and thigh profile with otherwise moderate upper-body measurements.",
    measurements: {
      sex: "female",
      height: 170,
      weight: 78,
      headCircumference: 55,
      neckCircumference: 34,
      biacromialWidth: 36,
      bideltoidWidth: 44,
      bideltoidCircumference: 102,
      armpitCircumference: 90,
      nippleCircumference: 92,
      underbustCircumference: 82,
      waistCircumference: 76,
      pantWaistCircumference: 86,
      hipCircumference: 118,
      upperThighCircumference: 72,
      midThighCircumference: 61,
      calfCircumference: 40,
      ankleCircumference: 23,
      bicepCircumference: 29,
      upperForearmCircumference: 24,
      wristCircumference: 15
    }
  }),
  profile({
    id: "upper-body-dominant",
    label: "Upper-body dominant",
    description: "Broad shoulders and larger arms with comparatively moderate hip and leg spans.",
    measurements: {
      sex: "male",
      height: 176,
      weight: 88,
      headCircumference: 58,
      neckCircumference: 42,
      biacromialWidth: 44,
      bideltoidWidth: 59,
      bideltoidCircumference: 138,
      armpitCircumference: 116,
      nippleCircumference: 110,
      underbustCircumference: 102,
      waistCircumference: 82,
      pantWaistCircumference: 86,
      hipCircumference: 96,
      upperThighCircumference: 58,
      midThighCircumference: 50,
      calfCircumference: 39,
      ankleCircumference: 23,
      bicepCircumference: 46,
      upperForearmCircumference: 36,
      wristCircumference: 18
    }
  }),
  profile({
    id: "weight-loss-return",
    label: "Weight-loss return",
    description: "User tracking a return-to-form goal after weight gain or life-event disruption.",
    measurements: {
      sex: "female",
      height: 164,
      weight: 74,
      headCircumference: 55,
      neckCircumference: 35,
      biacromialWidth: 36,
      bideltoidWidth: 45,
      bideltoidCircumference: 106,
      armpitCircumference: 96,
      nippleCircumference: 101,
      underbustCircumference: 88,
      waistCircumference: 88,
      pantWaistCircumference: 94,
      hipCircumference: 108,
      upperThighCircumference: 63,
      midThighCircumference: 54,
      calfCircumference: 38,
      ankleCircumference: 22,
      bicepCircumference: 32,
      upperForearmCircumference: 26,
      wristCircumference: 16
    }
  }),
  profile({
    id: "transition-tracker",
    label: "Transition tracker",
    description: "Moderate profile useful for checking softer waist, hip, shoulder, and chest changes over time.",
    measurements: {
      sex: "female",
      height: 173,
      weight: 68,
      headCircumference: 56,
      neckCircumference: 32,
      biacromialWidth: 38,
      bideltoidWidth: 46,
      bideltoidCircumference: 102,
      armpitCircumference: 88,
      nippleCircumference: 93,
      underbustCircumference: 80,
      waistCircumference: 72,
      pantWaistCircumference: 80,
      hipCircumference: 99,
      upperThighCircumference: 56,
      midThighCircumference: 48,
      calfCircumference: 35,
      ankleCircumference: 21,
      bicepCircumference: 28,
      upperForearmCircumference: 23,
      wristCircumference: 15
    }
  })
];

export function getSilhouetteQaProfile(id) {
  return silhouetteQaProfiles.find((candidate) => candidate.id === id) || null;
}
